"""add preleve_par to examens

Revision ID: 4f154dbbc702
Revises: 9bcf14c6035d
Create Date: 2026-07-01 16:15:44.600740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f154dbbc702'
down_revision = '9bcf14c6035d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preleve_par', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.drop_column('preleve_par')

    # ### end Alembic commands ###
