"""Initial - toutes les tables RyvixLab

Revision ID: 52d98c92ab3e
Revises: 
Create Date: 2026-05-11 19:35:40.077142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d98c92ab3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.CheckConstraint('prix >= 0', name='check_analyse_prix_positif'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_nom'), ['nom'], unique=True)
        batch_op.create_index(batch_op.f('ix_analyses_service'), ['service'], unique=False)

    op.create_table('laboratoire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('slogan', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('telephone1', sa.String(length=30), nullable=True),
    sa.Column('telephone2', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('site_web', sa.String(length=150), nullable=True),
    sa.Column('directeur_nom', sa.String(length=150), nullable=True),
    sa.Column('directeur_titre', sa.String(length=100), nullable=True),
    sa.Column('directeur_signature_path', sa.String(length=255), nullable=True),
    sa.Column('numero_licence', sa.String(length=50), nullable=True),
    sa.Column('numero_fiscal', sa.String(length=50), nullable=True),
    sa.Column('en_tete_couleur', sa.String(length=20), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=True),
    sa.Column('pied_page', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('standard', 'administrateur')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('nom_parametre', sa.String(length=100), nullable=False),
    sa.Column('sous_parametre', sa.String(length=100), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=True),
    sa.Column('valeur_normale_f', sa.String(length=50), nullable=True),
    sa.Column('valeur_normale_m', sa.String(length=50), nullable=True),
    sa.Column('valeur_normale_enfant', sa.String(length=50), nullable=True),
    sa.Column('type_resultat', sa.String(length=20), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parametres_analyse_id'), ['analyse_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('sexe', sa.String(length=1), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("sexe IN ('M', 'F') OR sexe IS NULL", name='check_patient_sexe'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patient_nom_date', ['nom_complet', 'date_creation'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_code'), ['code'], unique=True)

    op.create_table('examens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date_examen', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('medecin_prescripteur', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.CheckConstraint("statut IN ('en_attente', 'en_cours', 'termine', 'imprime', 'annule')", name='check_examen_statut'),
    sa.CheckConstraint('total >= 0', name='check_examen_total_positif'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_examens_date_examen'), ['date_examen'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_examens_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_examens_statut'), ['statut'], unique=False)

    op.create_table('examen_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('analyse_id', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acheve', sa.Boolean(), nullable=False),
    sa.Column('date_achevement', sa.DateTime(), nullable=True),
    sa.CheckConstraint('prix_unitaire >= 0', name='check_detail_prix_positif'),
    sa.ForeignKeyConstraint(['analyse_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('examen_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_examen_details_examen_id'), ['examen_id'], unique=False)

    op.create_table('journal_caisse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type_operation', sa.String(length=20), nullable=False),
    sa.Column('mode_paiement', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('date_operation', sa.DateTime(), nullable=False),
    sa.Column('enregistre_par', sa.Integer(), nullable=True),
    sa.CheckConstraint("mode_paiement IN ('espece', 'cheque', 'virement', 'carte', 'moncash')", name='check_journal_mode'),
    sa.CheckConstraint("type_operation IN ('encaissement', 'remboursement', 'depense')", name='check_journal_type'),
    sa.CheckConstraint('montant > 0', name='check_journal_montant_positif'),
    sa.ForeignKeyConstraint(['enregistre_par'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_caisse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_caisse_date_operation'), ['date_operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_caisse_examen_id'), ['examen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_caisse_type_operation'), ['type_operation'], unique=False)

    op.create_table('resultats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_detail_id', sa.Integer(), nullable=False),
    sa.Column('parametre_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.String(length=200), nullable=True),
    sa.Column('statut_valeur', sa.String(length=20), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_saisie', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('saisi_par', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['examen_detail_id'], ['examen_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parametre_id'], ['parametres.id'], ),
    sa.ForeignKeyConstraint(['saisi_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultats_examen_detail_id'), ['examen_detail_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultats_examen_detail_id'))

    op.drop_table('resultats')
    with op.batch_alter_table('journal_caisse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_caisse_type_operation'))
        batch_op.drop_index(batch_op.f('ix_journal_caisse_examen_id'))
        batch_op.drop_index(batch_op.f('ix_journal_caisse_date_operation'))

    op.drop_table('journal_caisse')
    with op.batch_alter_table('examen_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examen_details_examen_id'))

    op.drop_table('examen_details')
    with op.batch_alter_table('examens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_examens_statut'))
        batch_op.drop_index(batch_op.f('ix_examens_patient_id'))
        batch_op.drop_index(batch_op.f('ix_examens_numero'))
        batch_op.drop_index(batch_op.f('ix_examens_date_examen'))

    op.drop_table('examens')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_code'))
        batch_op.drop_index('idx_patient_nom_date')

    op.drop_table('patients')
    with op.batch_alter_table('parametres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parametres_analyse_id'))

    op.drop_table('parametres')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('laboratoire')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_service'))
        batch_op.drop_index(batch_op.f('ix_analyses_nom'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
