"""Ajout table valeurs_predefinies

Revision ID: 9bcf14c6035d
Revises: 52d98c92ab3e
Create Date: 2026-05-19 15:53:48.290044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcf14c6035d'
down_revision = '52d98c92ab3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valeurs_predefinies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parametre_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parametre_id'], ['parametres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valeurs_predefinies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valeurs_predefinies_parametre_id'), ['parametre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valeurs_predefinies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valeurs_predefinies_parametre_id'))

    op.drop_table('valeurs_predefinies')
    # ### end Alembic commands ###
